### ISSUE TITLE
MissingSessionCookieError

### ISSUE THREAD

**Issue by kr0uthu** [Mariusz89B/plugin.video.viaplay#21]
Hej,

od kilku tygodni wtyczka przestała działać, wcześniej działała bez zarzutów. Wtyczka wykrzacza się z błędem zaraz po jej uruchomieniu.

Wydaje mi się, że problem występuje podczas logowania. Próbowałem logować się zarówno za pomocą linku, jak i podając login i hasło w konfiguracji wtyczki. Oba kończą się analogicznym wyjątkiem:
```
2023-05-18 02:32:40.832 T:15726   error <general>: GetDirectory - Error getting plugin://plugin.video.viaplay/
2023-05-18 02:32:40.838 T:15666   error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.viaplay/) failed
2023-05-18 02:33:43.445 T:15742   error <general>: GetDirectory - Error getting plugin://plugin.video.viaplay/
2023-05-18 02:33:43.457 T:15666   error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.viaplay/) failed
2023-05-18 02:34:30.451 T:15794   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'embedded'
                                                   Traceback (most recent call last):
                                                     File "/home/krouthu/.kodi/addons/plugin.video.viaplay/resources/lib/addon.py", line 190, in run
                                                       plugin.run()
                                                     File "/home/krouthu/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "/home/krouthu/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "/home/krouthu/.kodi/addons/plugin.video.viaplay/resources/lib/addon.py", line 351, in root
                                                       pages = helper.vp.get_root_page()
                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/krouthu/.kodi/addons/plugin.video.viaplay/resources/lib/viaplay.py", line 439, in get_root_page
                                                       raise self.ViaplayError('MissingSessionCookieError')  # raise error if user is not logged in
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   resources.lib.viaplay.Viaplay.ViaplayError: 'MissingSessionCookieError'
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/home/krouthu/.kodi/addons/plugin.video.viaplay/default.py", line 5, in <module>
                                                       addon.run()
                                                     File "/home/krouthu/.kodi/addons/plugin.video.viaplay/resources/lib/addon.py", line 196, in run
                                                       plugin.run()
                                                     File "/home/krouthu/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "/home/krouthu/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "/home/krouthu/.kodi/addons/plugin.video.viaplay/resources/lib/addon.py", line 369, in root
                                                       profiles_dict = helper.vp.get_profiles()
                                                                       ^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/krouthu/.kodi/addons/plugin.video.viaplay/resources/lib/viaplay.py", line 229, in get_profiles
                                                       if data['embedded'].get('profiles'):
                                                          ~~~~^^^^^^^^^^^^
                                                   KeyError: 'embedded'
                                                   -->End of Python script error report<--
                                                   
2023-05-18 02:34:30.485 T:15793   error <general>: GetDirectory - Error getting plugin://plugin.video.viaplay/
2023-05-18 02:34:30.493 T:15666   error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.viaplay/) failed
```

Korzystam z Kodi 20 na Arch Linuxie:
```
2023-05-18 02:32:33.736 T:15666    info <general>: Starting Kodi (20.1 (20.1.0) Git:20230507-nogitfound). Platform: Linux x86 64-bit
2023-05-18 02:32:33.736 T:15666    info <general>: Using Release Kodi x64
2023-05-18 02:32:33.736 T:15666    info <general>: Kodi compiled 2023-05-07 by GCC 13.1.1 for Linux x86 64-bit version 6.3.0 (393984)
2023-05-18 02:32:33.736 T:15666    info <general>: Running on Arch Linux 0.0, kernel: Linux x86 64-bit version 6.3.1-arch2-1
2023-05-18 02:32:33.736 T:15666    info <general>: FFmpeg version/source: 4.4.1-Kodi
2023-05-18 02:32:33.736 T:15666    info <general>: Host CPU: Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz, 8 cores available
```

**Comment by Mariusz89B** [comment]
Spróbuje naprawić w wolnym czasie.

**Comment by Mariusz89B** [comment]
@kr0uthu Sprawdz czy dziala w wersji beta v3, wyglada na to ze wtyczka nie wczytuje poprawnie konto urzytkownika. Probowalem u siebie odtworzyc problem ale nie udalo mi sie.
https://github.com/Mariusz89B/plugin.video.viaplay/releases/tag/v2.4.6_v3

**Comment by kr0uthu** [comment]
@Mariusz89B tak, działa bez zarzutów. Dzięki!
